syntax = "proto3";

package token;

service TokenService {
  rpc GenerateToken (GenerateTokenRequest) returns (GenerateTokenResponse) {}
  rpc VerifyToken (VerifyTokenRequest) returns (VerifyTokenResponse) {}
}

message GenerateTokenRequest {
  int32 user_id = 1;
  string email = 2;
}

message GenerateTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
  string expires_at = 3;
}

message VerifyTokenRequest {
  string token = 1;
}

message VerifyTokenResponse {
  bool valid = 1;
  int32 user_id = 2;
  string email = 3;
}
